[project]
name = "helmet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.1.0",
    "mcp>=2.1.1",
    "prefect>=3.8.4",
    "supabase>=2.31.0",
]

[project.scripts]
helmet = "helmet:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
